import { assertEquals, assertNotEquals } from 'https://deno.land/std@0.224.0/testing/asserts.ts'

// ============================================================================
// Pure functions extracted from generate-pdf/index.ts for unit testing.
// These are copied verbatim to validate correctness without triggering
// Deno.serve() side effects on import.
// ============================================================================

function escapePDF(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

interface PDFContent {
  title: string
  subtitle?: string
  businessName: string
  period?: string
  sections: Array<{ title: string; rows: Array<{ label: string; amount: string; isTotal?: boolean }> }>
  integrityHash?: string
}

function generatePDF(content: PDFContent): string {
  const lineHeight = 14, pageWidth = 612, leftMargin = 50, rightMargin = pageWidth - 50
  let yPos = 750, contentStream = 'BT\n'

  contentStream += `/F1 18 Tf\n${leftMargin} ${yPos} Td\n(${escapePDF(content.title)}) Tj\n`; yPos -= 30
  if (content.subtitle) { contentStream += `/F1 10 Tf\n0 -20 Td\n(${escapePDF(content.subtitle)}) Tj\n`; yPos -= 20 }
  contentStream += `/F1 12 Tf\n0 -25 Td\n(${escapePDF(content.businessName)}) Tj\n`; yPos -= 40
  if (content.period) { contentStream += `/F1 10 Tf\n0 -15 Td\n(Period: ${escapePDF(content.period)}) Tj\n`; yPos -= 20 }
  contentStream += 'ET\nq\n0.5 w\n'; contentStream += `${leftMargin} ${yPos} m ${rightMargin} ${yPos} l S\nQ\nBT\n`; yPos -= 30

  for (const section of content.sections) {
    contentStream += `/F1 12 Tf\n${leftMargin} ${yPos} Td\n(${escapePDF(section.title)}) Tj\n`; yPos -= 20
    contentStream += `/F1 10 Tf\n`
    for (const row of section.rows) {
      contentStream += `0 -${lineHeight} Td\n`
      const prefix = row.isTotal ? '' : '  '
      contentStream += `(${prefix}${escapePDF(row.label)}) Tj\n`
      const amountWidth = row.amount.length * 6
      contentStream += `${rightMargin - leftMargin - amountWidth - 60} 0 Td\n(${escapePDF(row.amount)}) Tj\n`
      contentStream += `${-(rightMargin - leftMargin - amountWidth - 60)} 0 Td\n`
      yPos -= lineHeight
    }
    yPos -= 15
  }

  yPos = 50; contentStream += `/F1 8 Tf\n${leftMargin} ${yPos} Td\n(Generated by Soledgic | ${new Date().toISOString().split('T')[0]}) Tj\n`
  if (content.integrityHash) contentStream += `0 -12 Td\n(Integrity Hash: ${content.integrityHash.slice(0, 32)}...) Tj\n`
  contentStream += 'ET'

  const objects = [
    `1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj`,
    `2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj`,
    `3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj`,
    `4 0 obj\n<< /Length ${contentStream.length} >>\nstream\n${contentStream}\nendstream\nendobj`,
    `5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj`
  ]

  let pdf = '%PDF-1.4\n'; const xrefOffsets: number[] = []
  for (const obj of objects) { xrefOffsets.push(pdf.length); pdf += obj + '\n' }
  const xrefStart = pdf.length
  pdf += 'xref\n'; pdf += `0 ${objects.length + 1}\n`; pdf += '0000000000 65535 f \n'
  for (const offset of xrefOffsets) pdf += offset.toString().padStart(10, '0') + ' 00000 n \n'
  pdf += 'trailer\n'; pdf += `<< /Size ${objects.length + 1} /Root 1 0 R >>\n`; pdf += 'startxref\n'; pdf += xrefStart + '\n'; pdf += '%%EOF'
  return btoa(pdf)
}

const VALID_REPORT_TYPES = ['creator_statement', 'profit_loss', 'balance_sheet', 'trial_balance', '1099', '1099_nec_form', 'reconciliation_summary']

function isValidInternalCall(authHeader: string | null, serviceKey: string | undefined): boolean {
  if (!authHeader) return false
  if (!serviceKey || serviceKey.length < 20) return false
  const token = authHeader.replace('Bearer ', '').trim()
  if (token.length !== serviceKey.length) return false
  let result = 0
  for (let i = 0; i < token.length; i++) {
    result |= token.charCodeAt(i) ^ serviceKey.charCodeAt(i)
  }
  return result === 0
}

// ============================================================================
// escapePDF
// ============================================================================

Deno.test('escapePDF: escapes backslashes', () => {
  assertEquals(escapePDF('back\\slash'), 'back\\\\slash')
})

Deno.test('escapePDF: escapes parentheses', () => {
  assertEquals(escapePDF('(hello)'), '\\(hello\\)')
})

Deno.test('escapePDF: handles mixed special characters', () => {
  assertEquals(escapePDF('a\\b(c)d'), 'a\\\\b\\(c\\)d')
})

Deno.test('escapePDF: passes through safe strings', () => {
  assertEquals(escapePDF('Hello World 123'), 'Hello World 123')
})

Deno.test('escapePDF: handles empty string', () => {
  assertEquals(escapePDF(''), '')
})

// ============================================================================
// generatePDF
// ============================================================================

Deno.test('generatePDF: returns valid base64 starting with PDF header', () => {
  const result = generatePDF({
    title: 'Test Report',
    businessName: 'Test Corp',
    sections: [],
  })
  const decoded = atob(result)
  assertEquals(decoded.startsWith('%PDF-1.4'), true)
  assertEquals(decoded.endsWith('%%EOF'), true)
})

Deno.test('generatePDF: includes title in content', () => {
  const result = generatePDF({
    title: 'Revenue Report',
    businessName: 'Soledgic',
    sections: [],
  })
  const decoded = atob(result)
  assertEquals(decoded.includes('Revenue Report'), true)
  assertEquals(decoded.includes('Soledgic'), true)
})

Deno.test('generatePDF: includes section rows', () => {
  const result = generatePDF({
    title: 'Test',
    businessName: 'Corp',
    sections: [{
      title: 'REVENUE',
      rows: [{ label: 'Service Income', amount: '$1,200.00' }],
    }],
  })
  const decoded = atob(result)
  assertEquals(decoded.includes('REVENUE'), true)
  assertEquals(decoded.includes('Service Income'), true)
  assertEquals(decoded.includes('$1,200.00'), true)
})

Deno.test('generatePDF: includes subtitle when provided', () => {
  const result = generatePDF({
    title: 'Statement',
    subtitle: 'John Creator',
    businessName: 'Platform',
    sections: [],
  })
  const decoded = atob(result)
  assertEquals(decoded.includes('John Creator'), true)
})

Deno.test('generatePDF: includes period when provided', () => {
  const result = generatePDF({
    title: 'Report',
    businessName: 'Corp',
    period: '2026-01-01 to 2026-01-31',
    sections: [],
  })
  const decoded = atob(result)
  assertEquals(decoded.includes('Period: 2026-01-01 to 2026-01-31'), true)
})

Deno.test('generatePDF: includes integrity hash when provided', () => {
  const hash = 'abcdef0123456789abcdef0123456789abcdef01'
  const result = generatePDF({
    title: 'Report',
    businessName: 'Corp',
    sections: [],
    integrityHash: hash,
  })
  const decoded = atob(result)
  assertEquals(decoded.includes('Integrity Hash: abcdef0123456789abcdef01234567'), true)
})

Deno.test('generatePDF: escapes special characters in content', () => {
  const result = generatePDF({
    title: 'Report (Draft)',
    businessName: 'Corp\\Inc',
    sections: [],
  })
  const decoded = atob(result)
  assertEquals(decoded.includes('Report \\(Draft\\)'), true)
  assertEquals(decoded.includes('Corp\\\\Inc'), true)
})

Deno.test('generatePDF: produces valid xref table with 6 entries', () => {
  const result = generatePDF({
    title: 'Test',
    businessName: 'Corp',
    sections: [],
  })
  const decoded = atob(result)
  assertEquals(decoded.includes('0 6'), true)  // 5 objects + free entry
  assertEquals(decoded.includes('trailer'), true)
  assertEquals(decoded.includes('startxref'), true)
})

// ============================================================================
// VALID_REPORT_TYPES
// ============================================================================

Deno.test('VALID_REPORT_TYPES: contains all expected types', () => {
  assertEquals(VALID_REPORT_TYPES.includes('creator_statement'), true)
  assertEquals(VALID_REPORT_TYPES.includes('profit_loss'), true)
  assertEquals(VALID_REPORT_TYPES.includes('balance_sheet'), true)
  assertEquals(VALID_REPORT_TYPES.includes('trial_balance'), true)
  assertEquals(VALID_REPORT_TYPES.includes('1099'), true)
  assertEquals(VALID_REPORT_TYPES.includes('1099_nec_form'), true)
  assertEquals(VALID_REPORT_TYPES.includes('reconciliation_summary'), true)
})

Deno.test('VALID_REPORT_TYPES: rejects unknown types', () => {
  assertEquals(VALID_REPORT_TYPES.includes('invoice'), false)
  assertEquals(VALID_REPORT_TYPES.includes(''), false)
})

// ============================================================================
// isValidInternalCall (constant-time auth)
// ============================================================================

Deno.test('isValidInternalCall: rejects null auth header', () => {
  assertEquals(isValidInternalCall(null, 'some-service-key-that-is-long'), false)
})

Deno.test('isValidInternalCall: rejects when service key is not configured', () => {
  assertEquals(isValidInternalCall('Bearer some-token', undefined), false)
})

Deno.test('isValidInternalCall: rejects short service key', () => {
  assertEquals(isValidInternalCall('Bearer short', 'short'), false)
})

Deno.test('isValidInternalCall: rejects mismatched tokens', () => {
  const serviceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.correct-key'
  assertEquals(isValidInternalCall('Bearer wrong-token-here-different', serviceKey), false)
})

Deno.test('isValidInternalCall: accepts matching bearer token', () => {
  const serviceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.valid-service-key'
  assertEquals(isValidInternalCall(`Bearer ${serviceKey}`, serviceKey), true)
})

Deno.test('isValidInternalCall: rejects token that is a substring of service key', () => {
  const serviceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.valid-service-key'
  const partial = serviceKey.slice(0, 30)
  assertEquals(isValidInternalCall(`Bearer ${partial}`, serviceKey), false)
})

Deno.test('isValidInternalCall: rejects includes-style bypass with extra content', () => {
  const serviceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.valid-key'
  const padded = serviceKey + 'extra-chars'
  assertEquals(isValidInternalCall(`Bearer ${padded}`, serviceKey), false)
})
